name: Build and Publish Theme
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Install and Build 🛎🔧
        uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '17'
          check-latest: true
      - run: yarn install --frozen-lockfile
      - run: yarn run format:check
      - run: yarn run theme:compile
      - name: Deploy Compiled CSS 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: theme-files # The branch the action should deploy to.
          folder: public # The folder the action should deploy.
      - name: Deploy Documentation 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.8
        with:
          branch: theme-files # The branch the action should deploy to.
          folder: docs # The folder the action should deploy.
          target-folder: docs
